# Generated by Django 4.2.1 on 2023-06-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_rating_profile_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='review',
        ),
    ]
