# Generated by Django 4.2.1 on 2023-06-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
