# Generated by Django 4.2.1 on 2023-06-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
